AllCops:
  Exclude:
    - 'app/helpers/**/*'
    - 'app/channels/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'capistrano/**/*'
ClassAndModuleChildren:
  EnforcedStyle: compact
LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
Metrix/MethodLength:
  Max: 20
Metrix/AbcSize:
  Max: 20
AccessorMethodName:
  Enabled: false
Lambda:
  Enabled: false
