language: ruby
rvm: 2.4.3
services: mysql2
bundler_args: "--without development --deployment -j4"
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - cd capistrano
  - bundle install
  - cd ..
  - bundle exec rails db:setup

jobs:
  include:
    - stage: test
      script: bundle exec rails test
    - stage: production_deploy
      script:
        - cd capistrano
        - bundle install
        - bundle exec cap production deploy
    - stage: staging_deploy
      script:
        - cd capistrano
        - bundle install
        - bundle exec cap staging deploy

stages:
  - test
  - name: production_deploy
    if: branch = master
  - name: staging_deploy
    if: branch = development/v1.1.0
