version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/api
    ports:
      - 3000:3000
    extends:
      file: ./docker/mysql/password.yml
      service: password
