FROM ruby:2.3.3
 
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
 
ADD Gemfile /usr/src/app/
ADD Gemfile.lock /usr/src/app/
ADD ./docker/rails/start.sh /usr/src/app/bin/
RUN chmod +x /usr/src/app/bin/start.sh
RUN bundle install
 
ADD . /usr/src/app
 
RUN apt-get update && apt-get install -y nodejs --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y mysql-client --no-install-recommends && rm -rf /var/lib/apt/lists/*
 
EXPOSE 3000
CMD ["bin/start.sh"]
