# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37bc3181aea43d17a54975e5974dfab7afbb862695565143cbe88b652c9a6b98826085684ea38d63e04f0f8065339505fa8947d2cfb87623385e706dc28419af
  slack_webhook_url: https://hooks.slack.com/services/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
test:
  secret_key_base: b959d0253729b3feae05faf25138b1c2fab612baa7286b6e1b21329c7f41eba111b7492a274c9f3ec4404f80408717f5a4f3d80e5a66f4a4774e527ffe612e29
  slack_webhook_url: https://hooks.slack.com/services/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
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
staging:
  secret_key_base: <%= ENV["STAGING_SECRET_KEY_BASE"] %>
  slack_webhook_url: https://hooks.slack.com/services/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

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_webhook_url: https://hooks.slack.com/services/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
