require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
require 'capistrano/bundler'
require 'capistrano/rails'
require 'capistrano3/unicorn'
require 'capistrano/dotenv/tasks'

# require 'capistrano/sidekiq'
# require "whenever/capistrano"
require 'slackistrano/capistrano'

require './lib/base'
Dir.glob("lib/capistrano/tasks/*.cap").each { |r| import r }

require 'pry'
