# frozen_string_literal: true

source 'https://rubygems.org'
gem 'capistrano', '3.9.1'
gem 'capistrano-bundler'
gem 'capistrano-dotenv-tasks', require: false
gem 'capistrano-rails'
gem 'capistrano-rbenv'
gem 'dotenv'

# gem 'capistrano-sidekiq'
gem 'capistrano3-unicorn', git: 'https://github.com/tablexi/capistrano3-unicorn.git', branch: 'master'
# gem 'whenever', require: false

gem 'pry'
gem 'sitemap_generator'
gem 'slackistrano'
